//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisLab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://apps.clientline.lv/WebServices/Live.asmx")]
        public string VisLab_LoggingService_ClientLineService {
            get {
                return ((string)(this["VisLab_LoggingService_ClientLineService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vislab.morozov.lv/tracking/api/soap/mantisconnect.php")]
        public string VisLab_IssueTrackerService_MantisConnect {
            get {
                return ((string)(this["VisLab_IssueTrackerService_MantisConnect"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CountersReportControl_tbxFilter1 {
            get {
                return ((string)(this["CountersReportControl_tbxFilter1"]));
            }
            set {
                this["CountersReportControl_tbxFilter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountersReportControl_cbxColumnsList_SelectedIndex1 {
            get {
                return ((int)(this["CountersReportControl_cbxColumnsList_SelectedIndex1"]));
            }
            set {
                this["CountersReportControl_cbxColumnsList_SelectedIndex1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CountersReportControl_tbxFilter2 {
            get {
                return ((string)(this["CountersReportControl_tbxFilter2"]));
            }
            set {
                this["CountersReportControl_tbxFilter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountersReportControl_cbxColumnsList_SelectedIndex2 {
            get {
                return ((int)(this["CountersReportControl_cbxColumnsList_SelectedIndex2"]));
            }
            set {
                this["CountersReportControl_cbxColumnsList_SelectedIndex2"] = value;
            }
        }
    }
}
